"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { LockKeyhole } from "lucide-react";
import { PageHead } from "@/components/UI";
import { SITE_CONFIG } from "@/lib/config";

const stats=[["2,418","방문자","+12%"],["816","재방문자","33.7%"],["48","도움 요청","이번 달"],["31","도움 연결","연결률 65%"],["126","프로그램 신청","6개 프로그램"],["39","재능기부","+8명"],["27","기도 요청","내용 비공개"],["14","사람 연결 요청","내용 비공개"]];
type SafeError={status?:number;code:string;type?:string;param?:string;name?:string;message?:string};
type AiStatus={configured:boolean;openaiConnection?:"ok"|"error"|"not_configured";structuredAI?:"ok"|"error"|"not_configured"|"not_tested";heartLetter?:"live"|"fallback"|"demo";mode?:"live"|"fallback"|"demo";model?:string;error?:SafeError|null;attempts?:number;recovered?:boolean};
type PrayerDiagnostic={ok:boolean;stage:"environment"|"resend"|"complete";provider?:string;environment:{resendApiKey:boolean;recipientEmail:boolean;fromEmail:boolean};environmentName:string;recipientEmail:string|null;fromEmail:string|null;httpStatus?:number|null;emailId?:string;timestamp:string;testDomainRestriction?:boolean;error?:SafeError};

export default function Page(){
  const [pin,setPin]=useState(""); const [unlocked,setUnlocked]=useState(false); const [authError,setAuthError]=useState("");
  const [aiStatus,setAiStatus]=useState<AiStatus|null>(null); const [diagnosing,setDiagnosing]=useState(false);
  const [prayerDiagnostic,setPrayerDiagnostic]=useState<PrayerDiagnostic|null>(null); const [prayerDiagnosing,setPrayerDiagnosing]=useState(false); const [copied,setCopied]=useState(false);

  async function unlock(e:FormEvent){
    e.preventDefault();setAuthError("");
    const r=await fetch("/api/admin/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pin})});
    if(r.ok){setUnlocked(true);setPin("");const statusResponse=await fetch("/api/admin/ai-status");const status:AiStatus=await statusResponse.json().catch(()=>({configured:false}));setAiStatus(statusResponse.ok?status:{configured:false});}
    else setAuthError("관리자 PIN을 확인해주세요.");
  }
  async function diagnose(){setDiagnosing(true);try{const response=await fetch("/api/admin/ai-diagnostic",{method:"POST"});const result:AiStatus=await response.json();if(response.ok)setAiStatus(result);else throw new Error();}catch{setAiStatus(current=>({...current,openaiConnection:"error",structuredAI:"not_tested",heartLetter:"fallback",error:{code:"diagnostic_request_failed"},configured:current?.configured??false}));}finally{setDiagnosing(false);}}
  async function diagnosePrayer(){setPrayerDiagnosing(true);setCopied(false);try{const response=await fetch("/api/admin/prayer-email-diagnostic",{method:"POST"});const result:PrayerDiagnostic=await response.json();if(response.status===401){setUnlocked(false);setAuthError("관리자 세션이 만료되었습니다. 다시 로그인해주세요.");return;}setPrayerDiagnostic(result);}catch{setPrayerDiagnostic({ok:false,stage:"resend",environment:{resendApiKey:false,recipientEmail:false,fromEmail:false},environmentName:"unknown",recipientEmail:null,fromEmail:null,timestamp:new Date().toISOString(),error:{code:"browser_network_error",type:"connection_error",message:"진단 API에 연결할 수 없습니다."}});}finally{setPrayerDiagnosing(false);}}
  async function copyDiagnostic(){if(!prayerDiagnostic)return;const d=prayerDiagnostic;const output=["COMMON Prayer Email Diagnostic","",`Environment: ${d.environmentName}`,`RESEND_API_KEY: ${d.environment.resendApiKey?"configured":"not configured"}`,`PRAYER_RECIPIENT_EMAIL: ${d.environment.recipientEmail?"configured":"not configured"}`,`PRAYER_FROM_EMAIL: ${d.environment.fromEmail?"configured":"not configured"}`,"",`Provider: ${d.provider??"Resend"}`,`Stage: ${d.stage}`,`HTTP Status: ${d.httpStatus??"-"}`,`Error Code: ${d.error?.code??"-"}`,`Error Type: ${d.error?.type??"-"}`,`Error Message: ${d.error?.message??"-"}`,`Timestamp: ${d.timestamp}`].join("\n");await navigator.clipboard.writeText(output);setCopied(true);}
  if(!unlocked)return <><PageHead eyebrow="ADMIN DEMO" title="관리자 페이지" desc="관리자 PIN을 입력해주세요."/><section className="section"><form className="container card admin-gate form" onSubmit={unlock}><LockKeyhole/><div className="field"><label htmlFor="admin-pin">Admin PIN</label><input id="admin-pin" type="password" required value={pin} onChange={e=>setPin(e.target.value)} autoComplete="current-password"/></div>{authError&&<p className="notice">{authError}</p>}<button className="button">관리자 페이지 열기</button><small>PIN은 로그인 요청에만 사용되며, 이후 진단에는 안전한 HttpOnly 관리자 세션을 사용합니다.</small></form></section></>;

  const mode=(aiStatus?.heartLetter??aiStatus?.mode??"demo").toUpperCase();
  const label=(value:AiStatus["openaiConnection"]|AiStatus["structuredAI"])=>value==="ok"?"정상":value==="error"?"오류":value==="not_configured"?"설정되지 않음":"진단 필요";
  const active=(value:string|undefined)=>value==="ok"||value==="live";
  const d=prayerDiagnostic;
  const errorTitle=d?.httpStatus===401?"Resend 인증 실패":d?.httpStatus===403?"Resend 권한/발신자 오류":d?.httpStatus===429?"Resend 요청 제한":(d?.httpStatus??0)>=500?"Resend 서버 오류":d?.error?.code==="validation_error"?"Resend 요청 검증 실패":d?.error?.type==="connection_error"?"Resend 연결 오류":"이메일 시스템 오류";
  return <><PageHead eyebrow="ADMIN DEMO" title="이번 달 COMMON" desc="민감한 개인 내용 없이, 지역사회와 만든 연결을 익명화된 숫자로 살펴봅니다."/><section className="section"><div className="container">
    <section className="card ai-admin-card"><p className="eyebrow">AI 마음편지</p><h2>AI 마음편지 상태</h2><div role="status" aria-live="polite"><p className={`connection-status ${aiStatus?.configured?"on":""}`}>서버 API Key　● {aiStatus?.configured?"설정됨":"설정되지 않음"}</p><p className={`connection-status ${active(aiStatus?.openaiConnection)?"on":""}`}>OpenAI 연결　● {label(aiStatus?.openaiConnection)}</p><p className={`connection-status ${active(aiStatus?.structuredAI)?"on":""}`}>Structured AI　● {label(aiStatus?.structuredAI)}</p><p className={`connection-status ${mode==="LIVE"?"on":""}`}>현재 응답 모드　● {mode}</p><p><strong>Attempts</strong>　{aiStatus?.attempts??"-"}</p><p><strong>Recovered</strong>　{aiStatus?.recovered?"Yes":"No"}</p><p><strong>Model</strong>　{aiStatus?.model??"-"}</p>{aiStatus?.error&&<div className="notice"><p><strong>마지막 오류</strong></p><p>오류 코드　{aiStatus.error.code}</p></div>}</div><div className="inline-actions"><button className="button" type="button" onClick={diagnose} disabled={diagnosing}>{diagnosing?"진단 중…":aiStatus?.openaiConnection?"다시 진단":"AI 연결 진단"}</button><Link className="button secondary" href="/heart/letter">마음편지 확인</Link></div><p className="billing-note">진단은 서버에서 직접 연결을 검사하며 비밀 키와 사용자 내용은 표시하지 않습니다.</p></section>
    <section className="card ai-admin-card prayer-diagnostic-card"><p className="eyebrow">PRAYER REQUEST</p><h2>기도 요청 이메일 진단</h2><p className={`connection-status ${d?.ok?"on":""}`}>● {d?d.ok?"이메일 시스템 정상":"이메일 시스템 오류":"확인 전"}</p><div className="diagnostic-grid" role="status" aria-live="polite"><p><strong>Resend API Key</strong><span>● {d?d.environment.resendApiKey?"설정됨":"설정 안 됨":"확인 전"}</span></p><p><strong>수신 이메일</strong><span>● {d?d.environment.recipientEmail?"설정됨":"설정 안 됨":"확인 전"}</span></p><p><strong>발신 이메일</strong><span>● {d?d.environment.fromEmail?"설정됨":"설정 안 됨":"확인 전"}</span></p><p><strong>Resend 연결</strong><span>● {d?d.stage==="complete"?"정상":d.stage==="resend"?"오류":"확인 전":"확인 전"}</span></p><p><strong>실제 이메일 테스트</strong><span>● {d?d.ok?"성공":"실패":"확인 전"}</span></p></div><div className="diagnostic-details"><p><strong>Environment</strong>　{d?.environmentName??"확인 전"}</p><p><strong>수신</strong>　{d?.recipientEmail??"-"}</p><p><strong>발신</strong>　{d?.fromEmail??"-"}</p><p><strong>마지막 HTTP Status</strong>　{d?.httpStatus??"-"}</p><p><strong>마지막 오류 코드</strong>　{d?.error?.code??"-"}</p><p><strong>마지막 오류 메시지</strong>　{d?.error?.message??"-"}</p><p><strong>Resend Email ID</strong>　{d?.emailId??"-"}</p><p><strong>진단 시간</strong>　{d?.timestamp??"-"}</p></div>{d&&!d.ok&&<div className="notice"><p><strong>{errorTitle}</strong></p>{d.httpStatus===401&&<p>RESEND_API_KEY가 유효하지 않거나 권한 문제가 있습니다.</p>}{d.httpStatus===403&&<p>발신 주소 또는 도메인 인증 상태를 확인하세요.</p>}{d.testDomainRestriction&&<p>Resend 테스트 발신 주소 제한 가능성. 발신 도메인 인증이 필요할 수 있습니다.</p>}</div>}<div className="inline-actions"><button className="button" type="button" onClick={diagnosePrayer} disabled={prayerDiagnosing}>{prayerDiagnosing?"진단 중…":"이메일 연결 진단"}</button>{d&&!d.ok&&<button className="button secondary" type="button" onClick={copyDiagnostic}>{copied?"복사됨":"진단 결과 복사"}</button>}</div><p className="billing-note">실제 테스트 이메일 한 통을 발송합니다. API Key와 기도 요청 개인정보는 응답·복사·로그에 포함되지 않습니다.</p></section>
    <section className="card ai-admin-card"><h2>기도 요청 안내</h2><p><strong>Provider</strong>　Resend</p><p><strong>교회 홈페이지</strong>　<a className="church-link" href={SITE_CONFIG.churchUrl} target="_blank" rel="noreferrer">{SITE_CONFIG.churchName} ↗</a></p></section><span className="demo-label">DEMO DASHBOARD · 실제 운영 데이터가 아닙니다</span><div className="grid admin-grid" style={{marginTop:24}}>{stats.map(([n,l,x])=><article className="card admin-card" key={l}><small>{l}</small><b>{n}</b><small>{x}</small></article>)}</div><div style={{textAlign:"center",marginTop:70}}><Link href="/impact" className="button">Community Impact 보기</Link> <Link href="/" className="button secondary">사용자 화면 보기</Link></div>
  </div></section></>;
}
