"use client";
import Link from "next/link";
import { ArrowRight, CalendarDays, Coffee, Compass, Heart, Map, MessageCircleHeart, Network, Sparkles, Sun, Users } from "lucide-react";
import { emotions } from "@/lib/data";
import { Modal } from "@/components/UI";
import { useState } from "react";

const icons={Heart,Users,Coffee,Sparkles,Compass,Sun};
export default function Home(){const [emotion,setEmotion]=useState<typeof emotions[0]|null>(null);const [verse,setVerse]=useState(false);
return <>
 <section className="hero"><div className="hero-copy"><p className="eyebrow">Coffee · Community · Care</p><h1 className="display">우리 동네에서<br/>서로 연결되는 공간</h1><p className="lead">커피 한 잔에서 시작되는 작은 연결이<br/>누군가에게는 큰 도움이 될 수 있습니다.</p><a className="button" href="#explore">COMMON 둘러보기 <ArrowRight size={18}/></a></div><div className="hero-visual" aria-label="따뜻한 카페 공간을 표현한 이미지"><div className="cafe-scene"/><div className="hero-note">오늘도 편안히 머물다 가세요 ☕</div></div></section>
 <section className="section" id="explore"><div className="container"><div className="section-intro"><div><p className="eyebrow">A MOMENT FOR YOU</p><h2 className="section-title">오늘 당신에게 가장 필요한 것은 무엇인가요?</h2></div><p>지금 마음과 가장 가까운 단어를 골라보세요.</p></div><div className="grid emotion-grid">{emotions.map(e=>{const Icon=icons[e.icon as keyof typeof icons];return <button key={e.name} className="card emotion-card clickable" onClick={()=>{setEmotion(e);setVerse(false)}}><Icon/><div><h3>{e.name}</h3><p>{e.copy}</p></div></button>})}</div></div></section>
 <section className="section section-soft"><div className="container"><div className="section-intro"><div><p className="eyebrow">SPACE · PEOPLE · COMMUNITY · CIRCLE</p><h2 className="section-title">공간을 열고, 사람을 연결하고,<br/>함께 만든 가치를 다시 우리 동네로.</h2></div><p>종교와 관계없이 누구나 이용할 수 있습니다.</p></div><div className="grid community-home-grid"><Link href="/community" className="card clickable community-home-card featured"><CalendarDays/><p className="eyebrow">THIS WEEK</p><h3>이번 주 COMMON</h3><p>이번 주, 이곳에서 함께할 수 있는 작은 시간을 만나보세요.</p></Link><Link href="/space" className="card clickable community-home-card"><Map/><p className="eyebrow">SPACE</p><h3>COMMON SPACE</h3><p>모임과 생각이 시작될 수 있는 공간을 만나보세요.</p></Link><Link href="/table" className="card clickable community-home-card"><Coffee/><p className="eyebrow">TABLE</p><h3>COMMON TABLE</h3><p>오늘 당신에게 맞는 자리를 찾아보세요.</p></Link><Link href="/connect" className="card clickable community-home-card"><Network/><p className="eyebrow">CONNECT</p><h3>COMMON CONNECT</h3><p>어디에 물어봐야 할지 모를 때, 함께 길을 찾아드립니다.</p></Link><Link href="/impact" className="card clickable community-home-card featured"><Sparkles/><p className="eyebrow">OUR IMPACT</p><h3>함께 만든 변화</h3><p>이 공간에서 시작된 가치가 어떻게 다시 동네로 돌아가는지 확인해보세요.</p></Link></div></div></section>
 <section className="section"><div className="container"><div className="section-intro"><div><p className="eyebrow">A QUIET PLACE FOR YOU</p><h2 className="section-title">마음을 편하게 나눌 수 있는 곳</h2></div></div><div className="grid grid-2"><article className="card service-card"><div className="service-icon"><Heart/></div><h3>마음편지</h3><p>말하기 어려운 이야기를 편하게 남겨보세요.</p><Link href="/heart/letter" className="button secondary">마음 이야기하기 <ArrowRight size={17}/></Link></article><article className="card service-card"><div className="service-icon"><MessageCircleHeart/></div><h3>기도를 부탁하고 싶어요</h3><p>마음에 품고 있는 일이 있다면{`\n`}조용히 기도를 부탁할 수 있습니다.</p><Link href="/prayer" className="button">기도 요청하기 <ArrowRight size={17}/></Link></article></div></div></section>
 <Modal open={!!emotion} onClose={()=>setEmotion(null)}><p className="eyebrow">오늘의 마음 · {emotion?.name}</p><h2>{emotion?.name==="위로"?"오늘 조금 힘든 하루였나요?":`${emotion?.name}이 필요한 오늘이군요.`}</h2><p>잠시 머물러도 괜찮습니다.<br/>이 공간에서 조금이라도 마음이 편안해졌으면 좋겠습니다.</p><div className="modal-actions"><Link className="button" href="/heart/letter">AI와 잠깐 이야기하기</Link><button className="text-button" onClick={()=>setVerse(v=>!v)}>마음에 도움이 되는 성경의 한 문장 보기</button></div>{verse&&<div className="notice" style={{marginTop:18}}>“수고하고 무거운 짐 진 자들아 다 내게로 오라.”<br/><small>— 마태복음 11:28 · 원할 때만 열어보는 신앙 콘텐츠입니다.</small></div>}</Modal>
 </>}
