"use client";
import Link from "next/link";
import { ArrowRight, Coffee, Compass, HandHeart, Heart, Sparkles, Sun, Users } from "lucide-react";
import { emotions } from "@/lib/data";
import { Modal } from "@/components/UI";
import { useState } from "react";

const icons={Heart,Users,Coffee,Sparkles,Compass,Sun};
export default function Home(){const [emotion,setEmotion]=useState<typeof emotions[0]|null>(null);const [verse,setVerse]=useState(false);
return <>
 <section className="hero"><div className="hero-copy"><p className="eyebrow">Coffee · Community · Care</p><h1 className="display">우리 동네에서<br/>서로 연결되는 공간</h1><p className="lead">커피 한 잔에서 시작되는 작은 연결이<br/>누군가에게는 큰 도움이 될 수 있습니다.</p><a className="button" href="#explore">COMMON 둘러보기 <ArrowRight size={18}/></a></div><div className="hero-visual" aria-label="따뜻한 카페 공간을 표현한 이미지"><div className="cafe-scene"/><div className="hero-note">오늘도 편안히 머물다 가세요 ☕</div></div></section>
 <section className="section" id="explore"><div className="container"><div className="section-intro"><div><p className="eyebrow">A MOMENT FOR YOU</p><h2 className="section-title">오늘 당신에게 가장 필요한 것은 무엇인가요?</h2></div><p>지금 마음과 가장 가까운 단어를 골라보세요.</p></div><div className="grid emotion-grid">{emotions.map(e=>{const Icon=icons[e.icon as keyof typeof icons];return <button key={e.name} className="card emotion-card clickable" onClick={()=>{setEmotion(e);setVerse(false)}}><Icon/><div><h3>{e.name}</h3><p>{e.copy}</p></div></button>})}</div></div></section>
 <section className="section section-soft"><div className="container"><div className="section-intro"><div><p className="eyebrow">NEIGHBORS HELP NEIGHBORS</p><h2 className="section-title">작은 도움으로 가까워지는 우리</h2></div></div><div className="grid grid-2"><article className="card service-card"><div className="service-icon"><HandHeart/></div><h3>도움이 필요해요</h3><p>혼자 해결하기 어려운 작은 일이 있나요?{`\n`}우리 동네 누군가가 도울 수 있습니다.</p><Link href="/request-help" className="button">도움 요청하기 <ArrowRight size={17}/></Link></article><article className="card service-card"><div className="service-icon"><Sparkles/></div><h3>도움을 드릴 수 있어요</h3><p>당신이 가진 작은 재능이{`\n`}누군가에게는 큰 도움이 될 수 있습니다.</p><Link href="/share-talent" className="button secondary">재능 나누기 <ArrowRight size={17}/></Link></article></div></div></section>
 <section className="section"><div className="container"><div className="grid grid-3"><Link href="/community" className="card clickable"><p className="eyebrow">TOGETHER</p><h3>동네 프로그램</h3><p className="lead" style={{fontSize:14}}>배우고, 만나고, 함께 즐기는 프로그램을 확인하세요.</p></Link><Link href="/market" className="card clickable"><p className="eyebrow">SHARE</p><h3>나눔 장터</h3><p className="lead" style={{fontSize:14}}>필요한 물건과 시간을 이웃과 가볍게 나눠요.</p></Link><Link href="/impact" className="card clickable"><p className="eyebrow">OUR IMPACT</p><h3>함께 만든 변화</h3><p className="lead" style={{fontSize:14}}>COMMON이 동네와 함께 쌓은 연결을 살펴보세요.</p></Link></div></div></section>
 <Modal open={!!emotion} onClose={()=>setEmotion(null)}><p className="eyebrow">오늘의 마음 · {emotion?.name}</p><h2>{emotion?.name==="위로"?"오늘 조금 힘든 하루였나요?":`${emotion?.name}이 필요한 오늘이군요.`}</h2><p>잠시 머물러도 괜찮습니다.<br/>이 공간에서 조금이라도 마음이 편안해졌으면 좋겠습니다.</p><div className="modal-actions"><Link className="button" href="/heart">AI와 잠깐 이야기하기</Link><button className="text-button" onClick={()=>setVerse(v=>!v)}>마음에 도움이 되는 성경의 한 문장 보기</button></div>{verse&&<div className="notice" style={{marginTop:18}}>“수고하고 무거운 짐 진 자들아 다 내게로 오라.”<br/><small>— 마태복음 11:28 · 원할 때만 열어보는 신앙 콘텐츠입니다.</small></div>}</Modal>
 </>}
