"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { ProgramCard } from "@/components/CommunityCards";
import { commonWeeks } from "@/lib/community-data";
const weekHeading={past:"지난 COMMON",current:"이번 주 COMMON",upcoming:"예정된 COMMON"} as const;
export function CommonWeekExplorer(){
 const initialWeek=Math.max(0,commonWeeks.findIndex(week=>week.status==="current"));const [weekIndex,setWeekIndex]=useState(initialWeek);const [programPage,setProgramPage]=useState(0);const [isMobile,setIsMobile]=useState(false);const touchStart=useRef<number|null>(null);const week=commonWeeks[weekIndex];const pageSize=isMobile?1:2;const pageCount=Math.ceil(week.programs.length/pageSize);const programs=useMemo(()=>week.programs.slice(programPage*pageSize,(programPage+1)*pageSize),[pageSize,programPage,week]);
 useEffect(()=>{const media=window.matchMedia("(max-width: 800px)");const update=()=>setIsMobile(media.matches);update();media.addEventListener("change",update);return()=>media.removeEventListener("change",update)},[]);useEffect(()=>setProgramPage(0),[weekIndex,pageSize]);
 const changeWeek=(next:number)=>{setWeekIndex(next);setProgramPage(0)};const previousProgram=()=>setProgramPage(page=>Math.max(0,page-1));const nextProgram=()=>setProgramPage(page=>Math.min(pageCount-1,page+1));const finishSwipe=(end:number)=>{if(touchStart.current===null)return;const distance=end-touchStart.current;if(Math.abs(distance)>45)(distance<0?nextProgram:previousProgram)();touchStart.current=null};
 return <div className="common-explorer"><nav className="week-navigation" aria-label="COMMON 주차 탐색"><button type="button" onClick={()=>changeWeek(weekIndex-1)} disabled={weekIndex===0} aria-label="이전 COMMON 보기"><ChevronLeft size={18}/><span>이전 COMMON</span></button><div aria-live="polite">{week.startDate&&week.endDate&&<small>{week.startDate} – {week.endDate}</small>}<h2>{weekHeading[week.status]}</h2></div><button type="button" onClick={()=>changeWeek(weekIndex+1)} disabled={weekIndex===commonWeeks.length-1} aria-label="다음 COMMON 보기"><span>다음 COMMON</span><ChevronRight size={18}/></button></nav>{week.programs.length===0?<div className="common-empty" role="status"><b>아직 등록된 COMMON이 없습니다.</b><p>새로운 시간이 준비되면 이곳에서 알려드릴게요.</p></div>:<section className="program-carousel" aria-label={`${weekHeading[week.status]} 프로그램`}><div className="program-carousel-heading"><div><p className="eyebrow">PROGRAMS</p><h3>{weekHeading[week.status]}</h3></div>{pageCount>1&&<div className="program-controls"><button type="button" onClick={previousProgram} disabled={programPage===0} aria-label="이전 프로그램 보기"><ChevronLeft/></button><span aria-live="polite">{programPage+1} / {pageCount}</span><button type="button" onClick={nextProgram} disabled={programPage===pageCount-1} aria-label="다음 프로그램 보기"><ChevronRight/></button></div>}</div><div className="program-carousel-grid" onTouchStart={event=>touchStart.current=event.changedTouches[0].clientX} onTouchEnd={event=>finishSwipe(event.changedTouches[0].clientX)}>{programs.map(program=><ProgramCard key={`${week.weekId}-${program.title}`} program={program} status={week.status}/>)}</div></section>}</div>
}
