"use client";
import { FormEvent, useState } from "react";
import { CheckCircle2 } from "lucide-react";
import { connectCategories } from "@/lib/community-data";

function Sent({kind}:{kind:string}){return <div className="card request-success" role="status"><CheckCircle2/><h2>DEMO 신청이 접수되었습니다.</h2><p>{kind}은 공개되지 않으며, 실제 운영 전에는 관리자 접수 시스템 연결이 필요합니다.</p></div>}
export function SpaceRequestForm({spaceName}:{spaceName:string}){const [sent,setSent]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)};if(sent)return <Sent kind="공간 신청"/>;return <form className="card form request-form" onSubmit={submit}><span className="demo-label">DEMO FORM · 실제 접수 아님</span><h2>공간 사용 신청</h2><p className="card-copy">신청 후 관리자가 공간과 일정을 확인합니다. 온라인 결제는 진행하지 않습니다.</p><div className="field"><label>공간</label><input value={spaceName} readOnly/></div><div className="field"><label>이름</label><input required autoComplete="name"/></div><div className="form-row"><div className="field"><label>희망 날짜</label><input required type="date"/></div><div className="field"><label>희망 시간</label><input required type="text" placeholder="예: 14:00–16:00"/></div></div><div className="field"><label>사용 목적</label><textarea required placeholder="모임의 목적을 간단히 알려주세요."/></div><div className="field"><label>예상 인원</label><input required min="1" type="number"/></div><div className="field"><label>연락 방법</label><select required defaultValue=""><option value="" disabled>선택해주세요</option><option>이메일</option><option>문자</option><option>전화</option></select></div><div className="field"><label>선택한 연락처</label><input required placeholder="선택한 방법의 연락처만 입력해주세요"/></div><fieldset className="choice-section"><legend>이 모임을 동네 사람들에게도 열어볼까요?</legend><label className="choice"><input name="openness" type="radio" defaultChecked/> <span><b>PRIVATE</b><small>우리 모임만 사용할게요.</small></span></label><label className="choice"><input name="openness" type="radio"/> <span><b>COMMON OPEN</b><small>몇 자리를 이웃에게 열어둘게요. 관리자 검토와 승인 후 이번 주 COMMON에 등록됩니다.</small></span></label></fieldset><div className="field"><label>COMMON CIRCLE 관심 분야 (선택)</label><select defaultValue=""><option value="">의견을 남기지 않을게요</option><option>아이들과 청소년</option><option>어르신</option><option>어려운 이웃의 생활</option><option>청년의 새로운 시작</option><option>지역사회에 가장 필요한 곳</option></select></div><p className="privacy-note">입력 정보는 공간 신청 확인에만 사용하며 마음편지·기도요청·CONNECT 데이터와 결합하지 않습니다.</p><button className="button">관리자 확인 요청</button></form>}

export function ConnectRequestForm(){const [sent,setSent]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)};if(sent)return <Sent kind="COMMON CONNECT 요청"/>;return <form className="card form request-form" onSubmit={submit}><span className="demo-label">DEMO FORM · 실제 접수 아님</span><h2>첫 연결 요청하기</h2><p className="card-copy">COMMON은 직접 상담하거나 모든 문제를 해결하지 않습니다. 요청을 비공개로 확인한 뒤 무료 공공서비스부터 적절한 연결을 찾습니다.</p><div className="field"><label>도움 분야</label><select required defaultValue=""><option value="" disabled>분야를 선택해주세요</option>{connectCategories.map(([name])=><option key={name}>{name}</option>)}</select></div><div className="field"><label>간단한 요청 내용</label><textarea required placeholder="연결을 찾는 데 필요한 내용만 적어주세요. 주민등록번호·상세주소 등은 적지 마세요."/></div><div className="field"><label>원하는 연락 방법</label><select required defaultValue=""><option value="" disabled>선택해주세요</option><option>이메일</option><option>문자</option><option>전화</option></select></div><div className="field"><label>선택한 연락처</label><input required placeholder="선택한 방법의 연락처만 입력해주세요"/></div><p className="privacy-note">요청은 다른 사용자에게 공개되지 않으며, AI 대화·기도요청·공간 신청 데이터와 결합하지 않습니다.</p><button className="button">비공개 연결 요청</button></form>}
